name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [8, 11]
        suite: [check, integrationTest] # "jmh -Pjmh.iterations=1 -Pjmh.timeOnIteration=5s -Pjmh.warmupIterations=0"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: 1.${{ matrix.java_version }}
    - name: Build with Gradle
      run: ./gradlew -Ptests.timeout.multiplier=3 ${{ matrix.suite }}
